---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

When mapping the location of samples, we need to center the worldmap to the coordinates were the samples are from

```{r}
library(marmap)
library(tidyverse)
library(rgdal)
library(rnaturalearth)
library(mapdata)
library(metR)
library(raster)
library(here)
```

## Start with the location of the samples

Change this accordingly to the project at hand. Make sure latitude and longitude columns are labelled `lat` and `lon`

```{r samples}

eDNA.samples <- read_csv(here("data", "metadata.latlong.csv"))

 eDNA.samples %>% 
   rename(sample = plateid_tag) %>% 
   separate(sample, into = c("Host", "Station"), sep = "_", remove = F) %>% 
   distinct(sample, Host, Station, depth, longitud, latitude) -> metadata

metadata %>% 
  mutate (Host_name = case_when(Host == "Gb" ~ "Geodia barretti",
                                Host == "Gh" ~ "Geodia hentscheli", 
                                Host == "Gg" ~ "Geodia garoupa", 
                                Host == "Pv" ~ "Phakellia ventilabrum")) -> metadata


named_pull <- function(x, values_from, names_from){
names.output<- pull(x, {{names_from}})
output <- pull(x, {{values_from}})
names(output)<- names.output
return(output)
}


# Get the coordinates

metadata %>% 
  summarise_at(c("latitude", "longitud"),
               .funs = list( Max = ~ round( max(.x) + 1,0) ,
                             Min = ~ round( min(.x) - 1,0))) %>%
  pivot_longer(cols = everything(),names_to = "Corner",
               values_to = "Coordinates") %>%
  named_pull(Coordinates, Corner) -> limits.for.map


```

```{r bathymetry}
b = getNOAA.bathy(lon1 = limits.for.map["longitud_Max"] ,
                  lon2 = limits.for.map[ "longitud_Min" ]-3,
                  lat1 = limits.for.map["latitude_Min"]-1, 
                  lat2 = limits.for.map["latitude_Max"], 
                  resolution = 6)

b <- fortify(b)
b



slope <- terrain(rasterFromXYZ(b, crs = "+proj=longlat +datum=WGS84 +no_defs"), opt = "slope")
str(slope)
as.data.frame(as(slope, "SpatialPixelsDataFrame")) -> slope
```

```{r}




base_map <- ne_countries(scale="large",returnclass="sf")
sf::st_crs(base_map)




ggplot(base_map) +
  
  geom_raster(data = b %>%  filter (z < 0),
              aes(x=x, y=y, fill=z)) + 

  geom_sf() +
  
  coord_sf(xlim=c(limits.for.map["longitud_Min"]-3, limits.for.map["longitud_Max"]),ylim=c(limits.for.map["latitude_Min"]-1, limits.for.map["latitude_Max"]),expand=F) +

  # geom_contour(data = b %>%  filter (z < 0), 
  #              aes(x=x, y=y, z=z),
  #              breaks=c(  -50, -75),
  #              size=c(0.3),
  #              colour="grey")  +
  # geom_text_contour (data = b %>%  filter (z < 0,y < 47), 
  #              aes(x=x, y=y,   z = z),
  #              breaks=c( -50, -75),
  #             
  #              colour="black")+
  theme_minimal() +
  xlab("") +
  ylab("")  -> base_plot

write_rds(base_plot, "base_map.rds")
metadata %>% 
  distinct(latitude, longitud, Host_name) %>% 
  group_by(latitude, longitud) %>% 
  summarise(Host_name = paste(Host_name, collapse = " | ")) -> metadata_for_plot

#base_plot +
ggplot(metadata_for_plot) +
  geom_point(data = metadata_for_plot, aes(x= longitud, y = latitude),  color = "black", size = 3, position = "jitter") +
   geom_point(data = metadata_for_plot, aes(x= longitud, y = latitude, color = Host_name),  size = 2, position = "jitter") +
  theme(legend.text = element_text(face = "italic"),
        legend.position = "bottom") +
  guides(color = guide_legend(title.position = "top",
                              title = "Host species",
                              nrow = 2),
         fill = guide_legend(title = "depth") )

ggsave(here("figures", "map_each_host.png"))

base_plot +
  geom_point(data = eDNA.samples, aes(x= longitud, y = latitude), fill = "white", shape = 21, color = "black", size = 1) %>% 
  write_rds(here("Data", "base_plot_eDNA.rds"))
```

```{r}
ggplot(data = base_map)+
  geom_sf()+
   coord_sf(xlim=c(limits.for.map["lon_Min"], limits.for.map["lon_Max"]),ylim=c(limits.for.map["lat_Min"], limits.for.map["lat_Max"]),expand=F)
```
